services:
  api:
    image: trangpham340/zalopay-agent-api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8080:8080"
  ui:
    image: trangpham340/zalopay-agent-ui:latest
    build:
      context: .
      dockerfile: Dockerfile.ui
    environment:
      API_BASE_URL: http://api:8080
    ports:
      - "8501:8501"
    depends_on:
      - api
